window.SPECIAL_PRODUCTS = [
  {id:'p-alprazolam025',name:'Alprazolam 0.25 mg',detail:'Caja con 30 tabletas · Requiere receta médica',price:130,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-alprazolam05',name:'Alprazolam 0.50 mg',detail:'Caja con 30 tabletas · Requiere receta médica',price:197,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-alprazolam1',name:'Alprazolam 1 mg',detail:'Caja con 30 tabletas · Requiere receta médica',price:189,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-alprazolam2',name:'Alprazolam 2 mg',detail:'Caja con 30 tabletas · Requiere receta médica',price:283,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-axcion',name:'Axcion Fentermina 30 mg',detail:'Caja con 30 tabletas · Requiere receta médica',price:310,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-axcion-ap',name:'Axcion AP Fentermina 30 mg',detail:'Caja con 30 tabletas AP · Requiere receta médica',price:498,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-bromazepam',name:'Bromazepam 3 mg',detail:'Caja con 30 tabletas · Requiere receta médica',price:180,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-clonazepam-gotas',name:'Clonazepam gotas',detail:'Requiere receta médica',price:90,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-clonazepam-tabs',name:'Clonazepam tabletas',detail:'Requiere receta médica',price:90,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-diazepam',name:'Diazepam',detail:'Requiere receta médica',price:90,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-diazepam-tempus',name:'Diazepam 10 mg Tempus',detail:'Requiere receta médica',price:100,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-diazepam-amp',name:'Diazepam, 50 ampolletas',detail:'Requiere receta médica',price:580,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-esbecalps',name:'Esbecalps',detail:'Caja con 60 tabletas · Requiere receta médica',price:837,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-farmapram05',name:'Farmapram 0.50 mg',detail:'Alprazolam, caja con 30 tabletas · Requiere receta médica',price:256,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-farmapram2',name:'Farmapram 2 mg',detail:'Alprazolam, caja con 30 tabletas · Requiere receta médica',price:413,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-imipramina',name:'Imipramina 25 mg',detail:'Caja con 20 tabletas · Requiere receta médica',price:125,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-itravil',name:'Itravil Clobenzorex 30 mg',detail:'Caja con 60 cápsulas · Requiere receta médica',price:835,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-lose1',name:'Lose 1 mg',detail:'Requiere receta médica',price:243,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-lose2',name:'Lose 2 mg',detail:'Requiere receta médica',price:290,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-metilfenidato',name:'Metilfenidato 10 mg',detail:'Caja con 60 tabletas · Requiere receta médica',price:330,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-obeclox',name:'Obeclox',detail:'Caja con 60 cápsulas · Requiere receta médica',price:864,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-terfarmex',name:'Terfarmex Fentermina 15 mg',detail:'Requiere receta médica',price:228,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-tradea',name:'Tradea LP 20 mg',detail:'Metilfenidato de liberación prolongada, caja con 30 tabletas · Requiere receta médica',price:973,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-tramadol-para',name:'Tramadol / Paracetamol Alpharma',detail:'Requiere receta médica',price:75,category:'Medicamento especial',icon:'🔒',special:true},
  {id:'p-tramadol-gotas',name:'Tramadol en gotas Alpharma',detail:'Requiere receta médica',price:75,category:'Medicamento especial',icon:'🔒',special:true}
];
